### ISSUE TITLE
unable to save select dropdown value as boolean

### ISSUE THREAD

**Issue by montchr** [alleyinteractive/wordpress-fieldmanager#371]
Can I save a select dropdown value created with `Fieldmanager_Select` as a boolean?

I've tried numerous arrangements of keys/values and either the labels are messed up or the stored value is a string, not a boolean.

I'd expect there to be a way to do this, as I don't want to use radio buttons or checkboxes for this particular field.

This results in a stored value of "False" or "True", and labels of null or "1":

```php
        $exclude = new \Fieldmanager_Select( [
            'name' => 'exclude_from_home_stream',
            'options' => [
                'False' => false,
                'True' => true
            ]
        ] );
```

This results in a label of "False" or "True" and the value is the same, also a string, not a boolean:

```php
        $exclude = new \Fieldmanager_Select( [
            'name' => 'exclude_from_home_stream',
            'options' => [
                false => 'False',
                true => 'True'
            ]
        ] );
```

This results in the same as the previous example:

```php
        $exclude = new \Fieldmanager_Select( [
            'name' => 'exclude_from_home_stream',
            'options' => [
                0 => 'False',
                1 => 'True'
            ]
        ] );
```

**Comment by danielbachhuber** [comment]
The problem is that Fieldmanager treats zero-indexed arrays of options magically:

```
$keys = array_keys( $options );
$use_name_as_value = ( array_keys( $keys ) === $keys );
foreach ( $options as $k => $v ) {
	$this->add_option_data( $v, ( $use_name_as_value ? $v : $k ) );
}
```

This magic behavior transforms `[ foo, bar ]` into `[ foo => foo, bar => bar ]`. But, because PHP only supports integer and string types in keys, `[ false => foo, true => bar ]` is transformed into `[ foo => foo, bar => bar ]` too.

Unfortunately, this behavior was introduced in 191d6370b489ca0a2bf2e4e7bcd23727042e280e so there's no going back. One potential fix is to register your options in reverse order, and set `default=>false`.

```
$exclude = new \Fieldmanager_Select( [
    'name' => 'exclude_from_home_stream',
    'options' => [
        true => 'True',
        false => 'False',
    ],
    'default' => false,
] );
$exclude->add_meta_box( 'Exclude', 'post' );
```

Or, you could just use a checkbox.
