### ISSUE TITLE
load_field not returning array

### ISSUE THREAD

**Issue by ChaosExAnima** [alleyinteractive/wordpress-fieldmanager#377]
On line 123 of Fieldmanager_Context_Storable:
```php
return empty( $data ) ? null : reset( $data );
```
The `reset` is causing Group fields to fail on retrieval, as they are expecting an array value and receive just the first array value.

Removing the `reset` fixes this issue.

**Comment by mboynes** [comment]
Hi @ChaosExAnima,
The code you've highlighted should not be causing any data to not be loaded. Looking at it with [the larger context of the method](https://github.com/alleyinteractive/wordpress-fieldmanager/blob/master/php/context/class-fieldmanager-context-storable.php#L114-L127), you'll see that this is only the case if `$field->serialize_data` is true. In that circumstance, there should only ever be one stored meta entry, because the data gets serialized.

If you feel you've still encountered an error, can you please elaborate on the issue you're experiencing? It would help for me if you could:

1. provide all necessary code snippets for your field(s), so that I can attempt to replicate it,
2. provide any data or explanations for attempting to replicate (e.g. "go to the 'New Post' screen, add 3 fields, enter this data, and save"),
3. explain what you're expecting to see as a result, and
4. explain what you are seeing instead

Thanks!

**Comment by ChaosExAnima** [comment]
@mboynes - Sure!

Here's the code I'm using:
```php
$fm = new Fieldmanager_Group( array(
	'name'     => 'usat_author_group',
	'children' => array(
		'profile'    => new Fieldmanager_Media( array(
			'label'       => __( 'Profile Picture' ),
			'description' => __( 'If not set, uses Gravatar photo.' ),
		) ),
		'background' => new Fieldmanager_Media( array(
			'label' => __( 'Background Image' ),
		) ),
		'title'      => new Fieldmanager_Textfield( array(
			'label' => __( 'Title' ),
		) ),
	),
) );
$fm->add_user_form( 'Author Page Settings' );
```

What I see happening is that the data is being saved correctly, but when it's being pulled into the form for display, the `Fieldmanager_Group` is deserializing the data from `get_user_meta` (or actually, `get_user_attribute` as we're a WP.com site), and only the first value is getting returned to the `render_field` method, which proceeds to silently fail.

Is there a way to properly set the serialization for this data that I'm missing?

**Comment by mboynes** [comment]
Thanks for the code and the detail! Using your code, this works just fine for me on an empty theme with no other plugins active. Of course, I'm not using user attributes because it's my local environment -- are you able to replicate this outside of WordPress.com environment, where user meta would be used instead of user attributes?

**Comment by ChaosExAnima** [comment]
No, I haven't. Will test and see if that's the root cause.

**Comment by mboynes** [comment]
Thanks!

**Comment by ChaosExAnima** [comment]
Okay, think I figured it out. I tested with a regular WP instance, and you are correct- it works fine. I narrowed down the problem to specifically WP.com's `get_user_attribute`. Here's the code of what I have:
```php
function get_user_attribute( $user_id, $meta_key ) {
	if ( !$usermeta = get_user_meta( $user_id, $meta_key ) )
		return false;

	if ( count($usermeta) == 1 )
		return reset($usermeta);

	return $usermeta;
}
```
As you can see, it's running `reset` if there's only one field returned, and when FM runs `reset` again, that just returns the first value in the serialized array, and everything breaks.

I think either the fix can be done on WP.com's end, or in the FM code to check for this case. :)

**Comment by ChaosExAnima** [comment]
Issue has been patched. Closing issue.
