### ISSUE TITLE
Default sanitize function on richtextarea breaks autoembed

### ISSUE THREAD

**Issue by terrarum** [alleyinteractive/wordpress-fieldmanager#549]
The default sanitize function runs wpautop on any content added via a fieldmanager richtextarea, which saves your text to the database with paragraph tags. Normal WordPress functions do not do this; post_content is not saved with paragraph tags, these are added before render.

The unexpected presence of paragraph tags in fieldmanager-controlled fields breaks autoembed.

Looking at the [autoembed source](https://developer.wordpress.org/reference/classes/wp_embed/autoembed/) it looks like autoembed should work with p tags, but it did not work for me until I overrode the sanitize function to stop running wpautop before saving the text.

Is it perhaps an issue with potential for other side-effects that FieldManager saves data to the database in a slightly different format than WordPress itself does?

edit: accidentally a word

**Comment by dlh01** [comment]
Hi @terrarum,

My understanding is that Fieldmanager uses `wpautop()` so that the meta value automatically appears on output like it does to the user on input without a developer having to remember to modify the value. 

Overriding the sanitizing function is reasonable, too, but there would be backwards-compatibility problems with changing the FM default. (FM developers, please correct me on these points if I'm mistaken.)

Regarding the behavior of `WP_Embed::autoembed()`: Although I'm not certain whether that's a Fieldmanager issue, I would note that support for `<p>` tags was added only in WordPress 4.6. Are you running 4.6 or later?

**Comment by danielbachhuber** [comment]
> The default sanitize function runs wpautop on any content added via a, which saves your text to the database with paragraph tags. Normal WordPress functions do not do this; post_content is not saved with paragraph tags, these are added before render.

This is correct. I've run into this behavior before too.

Changing the behavior at this point seems like it runs the risk of opening up some unexpected bugs though.

**Comment by terrarum** [comment]
@dlh01 Turns out we're using 4.5.3 so that explains that. I am disappointed in myself for not thinking to check that haha.

Oh that makes sense, since any Fieldmanager content isn't in the WordPress lifecycle it wouldn't ever get wpautop run against it otherwise. Fair enough!

If nobody else is actually running into issues caused by that behaviour then it's probably not worth the hassle of changing it and risking other things breaking, and relying on devs remembering to remember to run wpautop against it.
